# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(960, 640)
        Main.setStyleSheet("background-color: rgb(234, 236, 235);")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.Lbl_Title = QtWidgets.QLabel(self.centralwidget)
        self.Lbl_Title.setGeometry(QtCore.QRect(30, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Lbl_Title.setFont(font)
        self.Lbl_Title.setStyleSheet("color: rgb(6, 106, 138);")
        self.Lbl_Title.setObjectName("Lbl_Title")
        self.Pnl_Main = QtWidgets.QFrame(self.centralwidget)
        self.Pnl_Main.setGeometry(QtCore.QRect(30, 120, 901, 491))
        self.Pnl_Main.setStyleSheet("border-radius: 10px;\n"
"border: 2px solid rgb(215, 229, 228);")
        self.Pnl_Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Pnl_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Pnl_Main.setObjectName("Pnl_Main")
        self.Pnl_Menu = QtWidgets.QFrame(self.Pnl_Main)
        self.Pnl_Menu.setGeometry(QtCore.QRect(10, 420, 881, 60))
        self.Pnl_Menu.setStyleSheet("border:6px;\n"
"background-color: rgb(243, 243, 243);")
        self.Pnl_Menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Pnl_Menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Pnl_Menu.setObjectName("Pnl_Menu")
        self.Btn_Capture = QtWidgets.QPushButton(self.Pnl_Menu)
        self.Btn_Capture.setGeometry(QtCore.QRect(420, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Capture.setFont(font)
        self.Btn_Capture.setStyleSheet("border:0px;\n"
"border-radius: 0px;\n"
"padding: 3px;\n"
"background-color: rgb(243, 243, 243);\n"
"")
        self.Btn_Capture.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Resources/photo_camera_48dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Capture.setIcon(icon)
        self.Btn_Capture.setIconSize(QtCore.QSize(41, 41))
        self.Btn_Capture.setObjectName("Btn_Capture")
        self.Btn_CameraOff = QtWidgets.QPushButton(self.Pnl_Menu)
        self.Btn_CameraOff.setGeometry(QtCore.QRect(320, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_CameraOff.setFont(font)
        self.Btn_CameraOff.setStyleSheet("border:0px;\n"
"border-radius: 0px;\n"
"padding: 3px;\n"
"background-color: rgb(243, 243, 243);\n"
"")
        self.Btn_CameraOff.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/Resources/videocam_off_48dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_CameraOff.setIcon(icon1)
        self.Btn_CameraOff.setIconSize(QtCore.QSize(41, 41))
        self.Btn_CameraOff.setObjectName("Btn_CameraOff")
        self.Btn_Switch = QtWidgets.QPushButton(self.Pnl_Menu)
        self.Btn_Switch.setGeometry(QtCore.QRect(520, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Switch.setFont(font)
        self.Btn_Switch.setStyleSheet("border:0px;\n"
"border-radius: 0px;\n"
"padding: 3px;\n"
"background-color: rgb(243, 243, 243);\n"
"")
        self.Btn_Switch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/Resources/cameraswitch_48dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Switch.setIcon(icon2)
        self.Btn_Switch.setIconSize(QtCore.QSize(41, 41))
        self.Btn_Switch.setObjectName("Btn_Switch")
        self.Btn_CameraOn = QtWidgets.QPushButton(self.Pnl_Menu)
        self.Btn_CameraOn.setGeometry(QtCore.QRect(320, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_CameraOn.setFont(font)
        self.Btn_CameraOn.setStyleSheet("border:0px;\n"
"border-radius: 0px;\n"
"padding: 3px;\n"
"background-color: rgb(243, 243, 243);\n"
"")
        self.Btn_CameraOn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/Resources/videocam_48dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_CameraOn.setIcon(icon3)
        self.Btn_CameraOn.setIconSize(QtCore.QSize(41, 41))
        self.Btn_CameraOn.setObjectName("Btn_CameraOn")
        self.Lbl_Menu = QtWidgets.QLabel(self.Pnl_Menu)
        self.Lbl_Menu.setGeometry(QtCore.QRect(60, 10, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.Lbl_Menu.setFont(font)
        self.Lbl_Menu.setStyleSheet("color: rgb(177, 177, 177);")
        self.Lbl_Menu.setObjectName("Lbl_Menu")
        self.Btn_Refresh = QtWidgets.QPushButton(self.Pnl_Menu)
        self.Btn_Refresh.setGeometry(QtCore.QRect(160, 10, 20, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Refresh.setFont(font)
        self.Btn_Refresh.setStyleSheet("border:0px;\n"
"border-radius: 0px;\n"
"padding: 3px;\n"
"background-color: rgb(243, 243, 243);\n"
"")
        self.Btn_Refresh.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icon/Resources/autorenew_48dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Refresh.setIcon(icon4)
        self.Btn_Refresh.setIconSize(QtCore.QSize(20, 20))
        self.Btn_Refresh.setObjectName("Btn_Refresh")
        self.Cam_View = QtWidgets.QLabel(self.Pnl_Main)
        self.Cam_View.setGeometry(QtCore.QRect(110, 20, 678, 381))
        self.Cam_View.setStyleSheet("border:0px;\n"
"border-radius: 0px;\n"
"padding: 3px;\n"
"background-color: rgb(234, 236, 235);\n"
"color: rgb(6, 106, 138);")
        self.Cam_View.setAlignment(QtCore.Qt.AlignCenter)
        self.Cam_View.setObjectName("Cam_View")
        self.Cam_Preview = QtWidgets.QLabel(self.Pnl_Main)
        self.Cam_Preview.setGeometry(QtCore.QRect(740, 320, 143, 80))
        self.Cam_Preview.setMinimumSize(QtCore.QSize(143, 80))
        self.Cam_Preview.setMaximumSize(QtCore.QSize(143, 80))
        self.Cam_Preview.setStyleSheet("border-radius: 10px;\n"
"color:rgb(238, 241, 250);")
        self.Cam_Preview.setAlignment(QtCore.Qt.AlignCenter)
        self.Cam_Preview.setObjectName("Cam_Preview")
        self.Cbx_Camera = QtWidgets.QComboBox(self.centralwidget)
        self.Cbx_Camera.setGeometry(QtCore.QRect(100, 570, 201, 21))
        self.Cbx_Camera.setStyleSheet("text-align: left;\n"
"padding-left: 10px;")
        self.Cbx_Camera.setFrame(False)
        self.Cbx_Camera.setObjectName("Cbx_Camera")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(810, 620, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(177, 177, 177);")
        self.label.setObjectName("label")
        Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.Lbl_Title.setText(_translate("Main", "Camera View"))
        self.Lbl_Menu.setText(_translate("Main", "Choose Camera"))
        self.Cam_View.setText(_translate("Main", "No Camera"))
        self.Cam_Preview.setText(_translate("Main", "No Preview"))
        self.label.setText(_translate("Main", "By @Machi-Za"))
import Res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
